language: node_js
node_js:
- '4.2'
script: true
sudo: false
deploy:
  provider: s3
  access_key_id: AKIAJ77G5SOMGZESAK7Q
  secret_access_key:
    secure: fNRIZWsVIi+mQ5G3uSsaRx9/P5pl5L2kqEeigx2n85Pvo+yjMbc9F1UYh3vxt8YJFyrjb6RuOIp4KzjzEvDPjTEs3K//pDxLX1UNulsY2hWUrrvj6g+u6Ra5xvHJYUQaAdMATzT22MgHOBFsv0kDrHWF8yY9KwYLfKCEG6N0Dhc=
  bucket: 2015.conference-agile.fr
  skip_cleanup: true
  endpoint: 2015.conference-agile.fr.s3-website.eu-central-1.amazonaws.com
  region: eu-central-1
  on:
    repo: agile-france/2015
    branch: s3
